Release/1.3.0
qbicsoftware/ukt-diagnostics-id-portlet pull request #12
Opened 2020-11-30 14:52 UTC by sven1103

The project structure is now based on Qube 2.6.1.

2020-11-30 14:53 UTC, sven1103 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update the CI framework for the ukt-diagnostics portlet](https://trello.com/c/dZVL7xMG/45-update-the-ci-framework-for-the-ukt-diagnostics-portlet)

2020-12-01 09:50 UTC, Steffengreiner requested changes
Very Nice! However i have some remarks concerning the versioning and the JDK documentation.

2020-12-01 09:50 UTC, Steffengreiner commented on .github/workflows/build_package.yml
> +      - name: Set up JDK 1.8
```suggestion
      - name: Set up JDK 1.11
```
Is this for backward compability reasons? I thought we agreed on JDK 11

2020-12-01 09:50 UTC, Steffengreiner commented on .github/workflows/build_package.yml
> +          java-version: 1.8
Is this for backward compability reasons? I thought we agreed on JDK 11
```suggestion
          java-version: 1.11
```

2020-12-01 09:50 UTC, Steffengreiner commented on .qube.yml
> +version: 1.3.0-SNAPSHOT
```suggestion
version: 1.3.0
```
Since this is intended for a release i'd remove the SNAPSHOT from the version 
I'd recommend the Qube bump-version functionality for this purpose.

2020-12-01 09:50 UTC, Steffengreiner commented on CHANGELOG.rst
> +1.3.0-SNAPSHOT (2020-11-30)
```suggestion
1.3.0 (2020-11-30)
```
I think the SNAPSHOT shuold be removed if this is intended for release? I'd recommend the Qube bump-version functionality for this purpose.

2020-12-01 09:50 UTC, Steffengreiner commented on README.rst
> +* TODO
```suggestion
```
This should maybe be adressed in a future PR. Having `ToDo` in the Readme seems wrong to me.

2020-12-01 09:50 UTC, Steffengreiner commented on docs/conf.py
> +version = '1.3.0-SNAPSHOT'
```suggestion
version = '1.3.0'
```
Since this is intended for a release i'd remove the SNAPSHOT from the version
I'd recommend the Qube bump-version functionality for this purpose.

2020-12-01 09:50 UTC, Steffengreiner commented on docs/conf.py
> +release = '1.3.0-SNAPSHOT'
```suggestion
release = '1.3.0'
```
Since this is intended for a release i'd remove the SNAPSHOT from the version
I'd recommend the Qube bump-version functionality for this purpose.

2020-12-01 09:50 UTC, Steffengreiner commented on qube.cfg
> +current_version = 1.3.0-SNAPSHOT
```suggestion
current_version = 1.3.0
```
Since this is intended for a release i'd remove the SNAPSHOT from the version
I'd recommend the Qube bump-version functionality for this purpose.

2020-12-01 10:11 UTC, Steffengreiner approved these changes
LGTM!

2020-12-01 11:41 UTC, merged