Replace ingestion for test sample
qbicsoftware/ukt-diagnostics-id-portlet pull request #15
Opened 2021-07-26 12:51 UTC by sven1103

Many thanks for contributing to this project!

**PR Checklist**
Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).

- [ ] This comment contains a description of changes (with reason)
- [ ] Referenced issue is linked
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Documentation in `docs` is updated
- [ ] `CHANGELOG.rst` is updated

**Description of changes**
Please state what you've changed and how it might affect the user.

**Technical details**
Please state any technical details such as limitations, reasons for additional dependencies, benchmarks etc. here.

**Additional context**
Add any other context or screenshots here.

2021-07-26 12:54 UTC, wow-such-code commented on src/main/java/life/qbic/BarcodeRequestModelImpl.java
> +        sampleCreation.setExperimentId(new ExperimentIdentifier(String.format("/%s/%s/%s", SPACE, CODE, "E3")));
is "CODE" the project?

2021-07-26 12:55 UTC, sven1103 commented on src/main/java/life/qbic/BarcodeRequestModelImpl.java
> +        sampleCreation.setExperimentId(new ExperimentIdentifier(String.format("/%s/%s/%s", SPACE, CODE, "E3")));
yes

2021-07-26 12:55 UTC, sven1103 commented on src/main/java/life/qbic/BarcodeRequestModelImpl.java
> +        sampleCreation.setExperimentId(new ExperimentIdentifier(String.format("/%s/%s/%s", SPACE, CODE, "E3")));
sorry, thats legacy bad naming

2021-07-26 15:49 UTC, wow-such-code commented on src/main/java/life/qbic/BarcodeRequestModelImpl.java
> +            int[] sizes = getNumberOfSampleTypes();
NIT: bad method name

2021-07-26 15:50 UTC, wow-such-code commented on src/main/java/life/qbic/BarcodeRequestModelImpl.java
> +            // offset is +2, because there is always an attachment sample per project
attachment sample has id 000, so it shouldn't matter

2021-07-26 15:50 UTC, wow-such-code commented on src/main/java/life/qbic/BarcodeRequestModelImpl.java
> +            // offset is +2, because there is always an attachment sample per project
wait, you don't offset by 2, so this comment is not needed

2021-07-26 15:51 UTC, wow-such-code commented on src/main/java/life/qbic/BarcodeRequestModelImpl.java
> +            patientSampleIdPair[1] = testSampleCodeTumor;
what about blood?

2021-07-26 15:54 UTC, wow-such-code commented on src/main/java/life/qbic/BarcodeRequestModelImpl.java
> +        int retryCount = 7;
this could take a whole minute, what about increasing the barcodes by 4 and the patient code by 1 every time it fails?

2021-07-26 16:09 UTC, wow-such-code requested changes
I have a few readability and user friendlyness concerns I would like to discuss, but I think this should work in any case.

2021-07-26 16:11 UTC, sven1103 commented on src/main/java/life/qbic/BarcodeRequestModelImpl.java
> +            patientSampleIdPair[1] = testSampleCodeTumor;
not displayed to the client because not relevant

2021-07-26 16:12 UTC, wow-such-code commented on src/main/java/life/qbic/BarcodeRequestModelImpl.java
> +        int retryCount = 7;
or you could even increment by 1, it would fail until the sample ids are free then

2021-07-27 08:26 UTC, wow-such-code commented on src/main/java/life/qbic/BarcodeRequestModelImpl.java
>          metadata.put("Q_NCBI_ORGANISM", "9606");
```suggestion
        //Human
        metadata.put("Q_NCBI_ORGANISM", "9606");
```

2021-07-27 08:29 UTC, wow-such-code commented on src/main/java/life/qbic/BarcodeRequestModelImpl.java
> +            if (!patientRegistered && !registerPatientOnly(patientId)) {
This already breaks before trying to register a patient twice, right? just making sure

2021-07-27 08:30 UTC, wow-such-code requested changes
looks very good to me, but please reply to/handle existing comments first

2021-07-27 08:33 UTC, sven1103 commented on src/main/java/life/qbic/BarcodeRequestModelImpl.java
> +        int retryCount = 7;
thread sleep down to 1000ms

2021-07-27 08:34 UTC, sven1103 commented on src/main/java/life/qbic/BarcodeRequestModelImpl.java
> +            // offset is +2, because there is always an attachment sample per project
agree

2021-07-27 08:35 UTC, sven1103 commented on src/main/java/life/qbic/BarcodeRequestModelImpl.java
> +            if (!patientRegistered && !registerPatientOnly(patientId)) {
in this case the first expression evaluates to false and the second expression is not resolved by the JRE anymore, since the AND condition can never be true anymore.

2021-07-27 08:36 UTC, wow-such-code commented on src/main/java/life/qbic/BarcodeRequestModelImpl.java
> +            if (!patientRegistered && !registerPatientOnly(patientId)) {
great!

2021-07-27 08:37 UTC, wow-such-code approved these changes
👍

2021-07-27 08:40 UTC, merged