Hotfix 1.2.9
qbicsoftware/ukt-diagnostics-id-portlet pull request #22
Opened 2021-12-21 08:02 UTC by jenniferboedker

1.2.8 (2021-12-20)
----------------------------------------------

**Added**

**Fixed**

* Fix CVE-2021-45105

**Dependencies**

* org.apache.logging.log4j:log4j-api: 2.16.0 -> 2.17.0
* org.apache.logging.log4j:log4j-core: 2.16.0 -> 2.17.0

2021-12-21 13:04 UTC, Steffengreiner requested changes
Very nice! 
I'll approve the PR once you also updated the Version indicated in the [life.qbic.AppInfo ](https://github.com/qbicsoftware/ukt-diagnostics-id-portlet/blob/master/src/main/java/life/qbic/AppInfo.java) class. 👍

2021-12-22 08:42 UTC, Steffengreiner requested changes
Heya @jenniferboedker. Thanks for adjusting the version in the AppInfo, could you do the same for the Changelog header? I just noticed it sorry 🙈

2021-12-22 08:42 UTC, Steffengreiner commented on CHANGELOG.rst
> +1.2.8 (2021-12-20)
Mb the correct version should also be mentioned in the changelog 👀 
```suggestion
1.2.9 (2021-12-20)
```

2021-12-22 08:51 UTC, jenniferboedker commented on CHANGELOG.rst
> +1.2.8 (2021-12-20)
NO!

2021-12-22 08:56 UTC, Steffengreiner commented on CHANGELOG.rst
> +1.2.8 (2021-12-20)
😿

2021-12-22 08:56 UTC, Steffengreiner approved these changes
LGTM 🚀

2021-12-22 10:07 UTC, merged